spring.application.name=HonestBiteAPI
spring.main.web-application-type=servlet
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/honestbite?useSSL=false&serverTimezone=UTC
spring.datasource.username=epic
spring.datasource.password=280520052
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
